### ISSUE TITLE
How can handle google.api_core.exceptions.BadRequest: 400 Unrecognized name: Error?

### ISSUE THREAD

**Issue by DevRockstarZ** [googleapis/python-bigquery#104]
I tried to handle wrong valued query errors.

My code is like this,

```
    try:
        query_job = client.query(query)  # Make an API request.
    except:
        print("Query Error...")
        result = None
```

And I manually send wrong query to my API,

but it raises google.api_core.exceptions.BadRequest: 400 Unrecognized name:

and my except part can't catch error.

**Comment by plamut** [comment]
@DevRockstarZ 

The posted try-except block is the most general possible and will catch _all_ exceptions raised in it. However, if a `BadRequest` manages to bubble up to the top, it probably happens in some other place in the code, outside of the try-except block.

Do you maybe try to specifically catch BadRequest errors, then inspect and handle them differently from other errors? Would something like the following do?
```py
from google.api_core import exceptions

try:
    query_job = client.query(query)  # Make an API request.
except exceptions.BadRequest as exc:
    # examine exc for details and handle the BadRequest error accordingly
except Exception:
    # handle all other exceptions
```

P.S.: It is usually better to catch general errors  with `except Exception:` rather than with a plain `except:` - the latter also catches exceptions such as `KeyboardInterrupt`, `SystemExit`, which normally shouldn't be swallowed.

**Comment by DevRockstarZ** [comment]
First, Thank you for your comment.
I tried to catch BadRequest errors only.
And I changed my code like this
```
    try:
        query_job = client.query(query)  # Make an API request.
    
    except exceptions.BadRequest as exc:
        return json.dumps({'message' : exc})
```
But it doesn't return json type error message and program exited with same error named 
"google.api_core.exceptions.BadRequest: 400 Unrecognized name:"
How can I solve it? Thanks.

**Comment by plamut** [comment]
Can you post the entire exception traceback to see more context?

From what I see in the second example, the error is in the `json.dumps()` line, because `BadRequest` objects are not JSON serializable out of the box, although it might not be the only error.

One way of getting around this particular error is to stringify the exception first:
```py
return json.dumps({'message' : str(exc)})
```

**Comment by DevRockstarZ** [comment]
Thank you for your comment again.

> Traceback (most recent call last):
>   File "/Users/imjuyeong/Desktop/get_user_wait_time.py", line 54, in <module>
>     print(get_user_wait_time({"hour": "25", "sex": "F",
>   File "/Users/imjuyeong/Desktop/get_user_wait_time.py", line 43, in get_user_wait_time
>     for row in query_job:
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/google/cloud/bigquery/job.py", line 3378, in __iter__
>     return iter(self.result())
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/google/cloud/bigquery/job.py", line 3196, in result
>     super(QueryJob, self).result(retry=retry, timeout=timeout)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/google/cloud/bigquery/job.py", line 818, in result
>     return super(_AsyncJob, self).result(timeout=timeout)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/google/api_core/future/polling.py", line 130, in result
>     raise self._exception
> google.api_core.exceptions.BadRequest: 400 Unrecognized name: ffff at [1:155]
> 
> (job ID: 155571b2-3ec6-4816-9af6-3d9dd7b6f7b5)
> 
>                                                                   -----Query Job SQL Follows-----                                                                  
> 
>     |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
>    1:SELECT WAIT_TIME FROM `connecting-208115.match_server.result` WHERE HOUR = 25 AND SEX = 'F' AND profile_level = 'B' AND call_type = 0 AND is_fast_match = ffff
>     |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
> imjuyeong@imjuyeocBookPro ~ %  env DEBUGPY_LAUNCHER_PORT=58722 /usr/local/bin/python3 /Users/imjuyeong/.vscode/extensions/ms-python.python-2020.4.76186/pythonFiles/lib/python/debugpy/no_wheels/debugpy/launcher /Users/imjuyeong/Desktop/get_user_wait_time.py 
> Traceback (most recent call last):
>   File "/Users/imjuyeong/Desktop/get_user_wait_time.py", line 54, in <module>
>     print(get_user_wait_time({"hour": "25", "sex": "F",
>   File "/Users/imjuyeong/Desktop/get_user_wait_time.py", line 43, in get_user_wait_time
>     for row in query_job:
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/google/cloud/bigquery/job.py", line 3378, in __iter__
>     return iter(self.result())
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/google/cloud/bigquery/job.py", line 3196, in result
>     super(QueryJob, self).result(retry=retry, timeout=timeout)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/google/cloud/bigquery/job.py", line 818, in result
>     return super(_AsyncJob, self).result(timeout=timeout)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/google/api_core/future/polling.py", line 130, in result
>     raise self._exception
> google.api_core.exceptions.BadRequest: 400 Unrecognized name: data at [1:155]

Is the full traceback for my code.
For example, in BigQuery table, there are boolean field and I made query for error handling and query for accessing wrong type. Like below.
`SELECT * FROM TABLE_NAME WHERE BOOLEAN_FIELD = 'data'`
I want to catch errors when user send wrong data to my python API.
The source code is deployed to my Google Cloud Function.
Thanks!

**Comment by plamut** [comment]
Thanks for the traceback, I can now see where the problem is.

The error happens outside of the the-except block, that's why it is not caught. It happens when iterating over query results in `get_user_wait_time.py`, line 43:
```py
for row in query_job:
```

The thing to note here is that `query_job` does not represent the query results themselves, but instead a job running the query on the server. Having a `query_job` instance at hand does not necessarily mean that the job has already completed, though, thus we first need to wait for that.

This is exactly what happens when [iterating](https://github.com/googleapis/python-bigquery/blob/834e2c032cd6303248d8bae952a8a8ada6d1c7e3/google/cloud/bigquery/job.py#L3375-L3376) over the query job instance directly - first, `result()` is called to wait for the results, and this is where the error is actually raised.

The easiest solutions is to call `query_job.result()` directly, catch and handle any errors, and then iterate over the result if all went fine.
```py
try:
    result = query_job.result()
except exceptions.BadRequest as exc:
    return json.dumps({'message' : str(exc)})

for row in result:
    ...
```

**Comment by DevRockstarZ** [comment]
Thanks! it worked perfect for me.
I thought client.query() send query to my BigQuery,
but as you commented,
```
for row in query_job:
 ...
```
sends the query and made the error.
So I changed the code the way you commented like this.
```
    try:
        for row in query_job:
            result = round(row[0])
    
    except exceptions.BadRequest as exc:
        return json.dumps({'error' : str(exc)})  
```
Thanks again with your great comment.
Have a nice day!

**Comment by plamut** [comment]
`client.query()` indeed sends the query to the server (which starts the query job there), but it does not contain query results, which is why `result()` needs to be called (either explicitly or implicitly when starting to iterate over it).

I'm glad that you managed to solve the problem and nice day to you, too!
