### ISSUE TITLE
Possibility of using fastparquet instead of pyarrow

### ISSUE THREAD

**Issue by Sampleqs** [googleapis/python-bigquery#1086]
Hello, I'm building a project that requires pure python library to DB processing, so I can't use pyarrow. I read in https://github.com/googleapis/python-bigquery/issues/376, https://github.com/googleapis/python-bigquery/issues/265
That from some version the fastparquet module was replaced with pyarrow. Can I use some previous versions of Google Bigquery to process data with fastparquet? Similar with pandas-gbq module.

Another solution is to use Firebase and automatically (!) without any scripts and manual commands export data to Google BigQuery tables.

What can I use in this case?

Thanks

**Comment by Sampleqs** [comment]
@tswast I can provide more information if it needs to resolve issue.

**Comment by tswast** [comment]
I don't believe fast parquet or even pandas is pure Python either, is it?

We also use pyarrow for pandas reads now (it's about 2x faster at combining multi-page results, plus we use it's robust schema support) so it would take quite a bit of refactoring to make pyarrow optional when used with pandas.

**Comment by Sampleqs** [comment]
> 

@tswast pandas has recipe, so it can be used. Idk about fast parquet, if it also working like some wrapper of C++ module or not pure Python it will write with same error. In this case maybe you'll recommend how to transfer data to BigQuery without pyarrow? Currently I know about Firebase possibility to store data, but the question is how automatically move data from Firebase to BigQuery as tables or lines.

**Comment by tswast** [comment]
Yes, fast parquet uses Cython to create a compiled package.

Your best bet is likely to use an older version of google-cloud-bigquery and the pandas-gbq package. It used to serialize to CSV by default and the latest version has an api_method="load_csv" option.

**Comment by Sampleqs** [comment]
> Your best bet is likely to use an older version of google-cloud-bigquery and the pandas-gbq package. It used to serialize to CSV by default and the latest version has an api_method="load_csv" option.

Thanks! Can you please say what is the latest version when was used fast parquet (not pyarrow)
`pip install google-cloud-bigquery==1.28.0 ?`

I also try pandas-gbq module, here is some remarks:
`import pandas_gbq
from google.oauth2 import service_account #to set credentials

credentials = service_account.Credentials.from_service_account_file('*.json')
pandas_gbq.to_gbq(self.df, project_id=project_id, destination_table=table_id_1, if_exists='append',credentials=credentials)
`
Currently to_gbq requires pyarrow too, so I don't know where pass this argument...
Can you please refer a link to this: api_method="load_csv" and maybe review what do I wrong. Thanks!

**Comment by tswast** [comment]
I believe you should be able to use as late a version as 2.1.0. `google-cloud-bigquery` 2.2.0 is the version that requires pyarrow in combination with pandas. https://github.com/googleapis/python-bigquery/blob/main/CHANGELOG.md#220-2020-10-19

> Can you please say what is the latest version when was used fast parquet (not pyarrow)

I think there was a mis-communication here. I'm suggesting you load dataframes via the CSV format, which requires neither fastparquet nor pyarrow.

To load via CSV, use `pandas-gbq` version 0.15.0 or earlier. Or, on the latest 0.16.0 version, https://github.com/googleapis/python-bigquery-pandas/blob/main/CHANGELOG.md#0160-2021-11-08 pass in `api_mthod="load_csv"`. https://googleapis.dev/python/pandas-gbq/latest/api.html#pandas_gbq.to_gbq

*Edit* On second thought, you're right that pyarrow is listed as a requirement in pandas-gbq (though I think this was added because there were some folks struggling with the transitive dependency from `google-cloud-bigquery`). You'll need to use `pandas-gbq` version 0.15.0 or earlier, which always writes via CSV.

**Comment by Sampleqs** [comment]
@tswast thanks for your attention and comment! I'll check both of modules and write back

**Comment by Sampleqs** [comment]
@tswast thanks again! Working, so guess the issue was solved.
