### ISSUE TITLE
provide "light" version of this package

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery#1142]
In certain use cases (limited compute resources), it would be useful to have just the REST API pieces without any protobuf, grpcio, pyarrow, pandas or other heavier dependencies.

CC @parthea

**Comment by majorgilles** [comment]
Concur with the post, we were using this as a replacement over the now bloated google-api-python-client and will be forced to pin this to the latest non problematic version because we use this from an AWS lambda environment which have very specific restricions in terms of deployment size

**Comment by benthorner** [comment]
Would love to see a "light" version of this package. 

v3 won't install on a Raspberry Pi due to the `pyarrow` dependency, which seems to lack a pre-compiled version for that architecture, which means trying (and failing) to compile it from source, etc.

I'm only using the client to insert some rows in a table, so really don't need all the extra bits. For now I've got it working by pinning to the last v2 version i.e. `pip install google-cloud-bigquery <3.0.0dev`.

**Comment by chalmerlowe** [comment]
Gonna close this item.

Rationale:

* By comparison, there are a number of open issues that currently have a higher priority/severity
* BigQuery itself consumes a lot of memory and is often not very well suited for IoT devices in general
* As we continue to migrate BigQuery toward a gRPC world, the optional dependencies will become less and less optional
* IoT is often about streaming data and a commonly recommended use case is to stream to a central application that then pushes data to BigQuery versus streaming directly from dozens/hundreds/thousands of small devices to BigQuery
* Having auth secrets stored directly on each IoT device is probably not the best idea

**Comment by tswast** [comment]
I believe this is fixed by https://github.com/googleapis/python-bigquery/pull/1721
