### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by benatkin** [googleapis/python-bigquery#1386]
Same request as https://github.com/googleapis/python-bigquery/issues/1006 but for 3.11

Luckily I'm not yet using 3.11, but I had to modify my `pyproject.yaml` to make [Poetry](https://python-poetry.org/) happy, and I probably will be using 3.11 soon

**Comment by joekohlsdorf** [comment]
The biggest blocker is going to be the `pyarrow` dependency which isn't overseen by the maintainers of this project.
It is essentially impossible to build on your own and there hasn't been much activity to make Python 3.11 wheels available.

**Comment by potiuk** [comment]
We are looking forwar to get this supported too in Apache Airflow. 

I know it is eaarly (Python 3.11 has just been released yesterday) but we are hoping in Apache Airflow to a much faster cycle of adding new Python releases - especially that Pyhon 3.11 introduces huge performance improvements (25% is the average number claimed) due to a very focused effort to increase single-threaded Python performance (Specialized interpreter being the core of it but also many other improvements) without actually changing any of the Python code.

I'd appreciate if someone in the Google team attempted to migrate and have a PR running (and failing possibly until all prerequisite are met so that we can also track the progress and possibly help each other to solve any problems. I know PyArrow is blocking for now, but this is going to be solved soon lilely with https://github.com/apache/arrow/pull/14499 and just opening a failing PR with it might be a good start.

I just opened such PR in Apache Airflow yesterday and plan to keep it open until it gets green :). So far google provider will need to be excluded there.

https://github.com/apache/airflow/pull/27264

I think it would be fantastic if we could as the open source community migrate to the new Python much faster.

Looking forward to cooperation on that one :)

**Comment by ad-m-ss** [comment]
FTR Upstream issue in pyarrow has been resolved ( apache/arrow/pull/14499 ), but still missing a compatible release of pyarrow ( https://pypi.org/project/pyarrow/#files )

**Comment by ad-m-ss** [comment]
FTR There is a compatible release of pyarrow (https://pypi.org/project/pyarrow/#files).

**Comment by pblankley** [comment]
Where is support for 3.11 on the roadmap? This would be super helpful 🙏

**Comment by PierrickV** [comment]
- https://github.com/googleapis/python-bigquery/pull/1454

**Comment by tswast** [comment]
Just released support in google-cloud-bigquery version 3.4.2. Thanks folks for your patience.

**Comment by potiuk** [comment]
Cooool.
