### ISSUE TITLE
Spaces removed from first item in list when using params in bigquery cell magic

### ISSUE THREAD

**Issue by laurao-wb** [googleapis/python-bigquery#1389]
When using a list in the parameters in bigquery cell magic, it seems that spaces are removed from the first item in the list. 

#### Environment details
Using Colab notebook
- Chrome Version 106.0.5249.119
- Python version: Python 3.7.15

  - pip version: 21.1.3 
  - google-cloud-bigquery Version: 3.3.5

#### Code example

```python
parameters = {
    "entry":["a b c", "d e f"]
}
```

```
%%bigquery --params $parameters
WITH temp_table AS(
  SELECT * FROM UNNEST(["a b c", "d e f", "g h i", "j k l", "abc"]) AS entry
)

SELECT * FROM temp_table
WHERE entry in UNNEST(@entry)
```

Expected output:
| entry | 
| ------------- | 
| a b c| 
| d e f | 

Actual output:
| entry | 
| ------------- | 
| d e f| 
| abc | 

If I do the same query without using parameters I get the expected result:
```
%%bigquery --params $parameters
WITH temp_table AS(
  SELECT * FROM UNNEST(["a b c", "d e f", "g h i", "j k l", "abc"]) AS entry
)

SELECT * FROM temp_table
WHERE entry in UNNEST(["a b c", "d e f"])
```

Thanks!

**Comment by alvarowolfx** [comment]
@laurao-wb I have tested here on Google Colab with `google-cloud-bigquery` v3.3.5 and v3.4.2 and the issue is not reproducible on my end. Are you using on a specific Jupyter Notebook version or are you using in Colab too ?

![Screenshot 2023-02-02 at 18 29 03](https://user-images.githubusercontent.com/1615543/216463975-2ee90238-abb4-4121-960c-c89eafebd747.png)
