### ISSUE TITLE
Expose jobTimeoutMs field in JobConfigurationQuery

### ISSUE THREAD

**Issue by aravindsrinivasan** [googleapis/python-bigquery#1421]
At job creation time I want to set a timeout for the job if it takes too long to run. Too many long running queries eat up the slot reservation and significantly deteriorates query performance. Currently we have to manually cancel the queries in the console. I noticed that there is a `jobTimeoutMs` field in the [JobConfiguration](https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#jobconfiguration) object. This is not exposed by the Python client but is exposed by other Bigquery clients ([Golang](https://github.com/googleapis/google-cloud-go/pull/5707)). Can we add this to the Python client as well?

The alternative would be to have a timer on the client side and manually cancel the request. This feels wasteful considering the feature already exists on the server side and it's just a question of exposing it in the client.

**Comment by tswast** [comment]
This could be another good project for the apprentices.

**Comment by tswast** [comment]
Since this applies to all job configurations, this would be a good fit to add to the _JobConfig base class here:

https://github.com/googleapis/python-bigquery/blob/1760e945d16163980027fecf21113cd77ddc35a1/google/cloud/bigquery/job/base.py#L153

**Comment by lbk-fishtown** [comment]
I've started a draft PR (#1656) for this issue. I have tested the the timeout works, but I could use some guidance (pointers to docs) on what is required test wise / how to add the required tests to this.

**Comment by dataders** [comment]
@colin-rogers-dbt shipped a fix for us in https://github.com/dbt-labs/dbt-bigquery/pull/902, but to reiterate, this is not the ideal place for the fix.

**Comment by chalmerlowe** [comment]
cc'ing @tswast. Tim, if my summation is mistaken, please feel free to correct me. 

@stokedout:

Regarding the word "might": many factors affect when Google's servers choose to stop a task. Some reasons a job may be stopped include:

* the query exceeds the execution time limit
* the API call exceeds the request time limit
* a query that is being run concurrently may exceed its query queue time limit
* if a continuous query begins to fall behind and a query's lag exceeds the limit 
* interactive queries have time limits that may be different than continuous queries

I could go on.

When Bigquery exceeds a user-set timeout, the service may not stop that job at exactly that second. There are server side operations and checks that must happen to trigger a job stoppage. Bigquery routinely checks the above conditions as well as the user's requested timeout to help it decide when to stop a job. The python bigquery client does not control that, those decisions are managed on the server side. I am not familiar enough with the internal workings to say more than that.

A semi-related note that represents the opposite issue: 

If a user tries to set a timeout using an attribute in our client (i.e. `job_config.job_timeout_ms`) we do not do any sort of client-side validation to ensure that the  user chose a value that does not exceed any of the other time limits that may play a role in controlling that job on the server side. A user may attempt to submit a timeout that exceeds a timeout limitation from the list above. The server handles the checks necessary to decide when to stop a job and may stop a job sooner than the user desires because of another time limit.
