### ISSUE TITLE
Need information on how to access INFORMATION_SCHEMA.JOBS_BY_ORGANIZATION

### ISSUE THREAD

**Issue by Sophyiya** [googleapis/python-bigquery#1524]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

I'm getting access denied error while accessing this view via python libraries. But I'm able to access them via console or run as a scheduled query. 

Below is the part of the code:

project_id = 'prj-analytics-bigquery-pp-dfd1'

client = bigquery.Client(project=project_id)
project = client.project

query = """SELECT project_id, user_email, creation_time, job_type, CASE WHEN statement_type IS NULL THEN 'N/A' ELSE statement_type END AS statement_type, error_result FROM `region-us.INFORMATION_SCHEMA.JOBS_BY_ORGANIZATION` WHERE error_result.reason in ('resourcesExceeded') and creation_time >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(),INTERVAL 1 hour)"""

query_job = client.query(query)

print("The query data:")
for row in query_job:
    print("project_id={}, user_email={}".format(row[0], row[1]))

Error:

403 Access Denied: Table prj-analytics-bigquery-pp-dfd1:region-us.INFORMATION_SCHEMA.JOBS_BY_ORGANIZATION: User does not have permission to query table prj-analytics-bigquery-pp-dfd1:region-us.INFORMATION_SCHEMA.JOBS_BY_ORGANIZATION, or perhaps it does not exist in location US.

**Comment by shollyman** [comment]
The likely cause is the client library is authenticated as a different identity than the one you use when accessing the console.  If you're running in a compute environment or a notebook, it may be the case that you're authenticated as a service account rather than as your end user credentials.

More details: https://cloud.google.com/docs/authentication/application-default-credentials
