### ISSUE TITLE
To get users in who has access to a columns 

### ISSUE THREAD

**Issue by Opperessor** [googleapis/python-bigquery#1536]
Due to the column-level access, is there a way to get all the columns that the user has access to?
Like UserA: TableA.Column1, TableA.Column2
UserB: TableA.Column1, TableA.Column3

**Comment by meredithslota** [comment]
This is described — sort of — in https://cloud.google.com/bigquery/docs/column-level-security-intro. That is, in order to get a user list like this, you'd look at the Data Policy Tags for which columns are impacted by which data policies, and then which users are granted access to which policy tags. 

Additional info here: https://cloud.google.com/bigquery/docs/best-practices-policy-tags The Python library for the BigQuery Data Policy API is here: https://github.com/googleapis/python-bigquery-datapolicies
