### ISSUE TITLE
Support jsonExtension in LoadJobConfig

### ISSUE THREAD

**Issue by bkanuka** [googleapis/python-bigquery#1581]
This would allow running the equivalent to:
```
bq load --source_format=NEWLINE_DELIMITED_JSON --json_extension=GEOJSON  <some>.<table>  <some_geojson_path>
```

**Comment by chalmerlowe** [comment]
Adding some notes for myself (and anyone who wants to tackle this):

Would need to take a look at LoadJobConfig and determine:
* Is this the right place to make these additions?
* What are the exact changes needed to add this feature?
* What tests need to be added to support testing of the new feature

**Comment by bkanuka** [comment]
I can't answer all your questions, but this workaround accomplishes what I want:
```
job_config = bigquery.LoadJobConfig(..., ..., ...)
job_config._set_sub_prop('jsonExtension', 'GEOJSON')
```

**Comment by chalmerlowe** [comment]
@bkanuka thanks for this additional context.

**Comment by kiraksi** [comment]
@chalmerlowe On this issue, how would you handle cases where we have two parameters passed in "sourceFormat" and "jsonExtension" with conflicting values, which should be prioritized? If sourceFormat is set to AUTODETECT, should we just fall back on the jsonExtension value? I am assuming since the jsonExtension value is more specific compared to sourceFormat, we would want to prioritize that if passed in, but not sure if that is definitely the case here.

**Comment by chalmerlowe** [comment]
@kiraksi 

We discussed this yesterday, but gonna add this note in case someone comes along after us and reads this issue.

These fields should be very different in focus:

* sourceFormat is used to identify what separates individual JSON records from each other
* jsonExtension is used to identify which type of records to expect (i.e. GEOJSON for geographical data). Specific JSON extensions may have defined datatypes that are not present in vanilla JSON.
