### ISSUE TITLE
Error while adding google-cloud-bigquery

### ISSUE THREAD

**Issue by mr-st0rm** [googleapis/python-bigquery#1603]
```
poetry add google-cloud-bigquery                                                                        

Using version ^3.11.3 for google-cloud-bigquery

Updating dependencies
Resolving dependencies...

Writing lock file

Package operations: 0 installs, 6 updates, 1 removal

  • Removing setuptools (67.6.0)
  • Updating protobuf (4.23.0 -> 4.23.3)

  JSONDecodeError

  Expecting value: line 1 column 1 (char 0)

  at C:\Python\lib\json\decoder.py:355 in raw_decode
      351│         """
      352│         try:
      353│             obj, end = self.scan_once(s, idx)
      354│         except StopIteration as err:
    → 355│             raise JSONDecodeError("Expecting value", s, err.value) from None
      356│         return obj, end
      357│


Failed to add packages, reverting the pyproject.toml file to its original content.

```
can u help me fix it, i'm trying add a package to poery in my pycharm console
python v- 3.10.7
but all services running in docker that use python 3.8
poetry versions on docker and local machine is same 1.1.8

**Comment by chalmerlowe** [comment]
Looking at this stacktrace/error message, it shows me:

The library for processing json in the Python Standard Library has run into a problem and is unable to decode some JSON that it has gotten. It is not clear what the problem might be, because I don't see the exact JSON to see what is wrong with it. Nor does it tell me where the JSON came from (i.e. which item produces the incorrectly formatted JSON) so we can go to the source to figure why it produced incorrect JSON.

It appears that poetry was able to figure out what files are needed as dependencies and to resolve any possible conflicts in version numbers between needed dependencies.

Beyond that, this is a problem with poetry performing it's job. I do not use poetry, nor do I have enough insight into how poetry works to be able to provide feedback.

I would suggest you work with one OR more of the following sources to help figure out what is going on:
* ask a similar question on stackoverflow.com
OR
* file a question on the poetry github repository

Because this is not inherently a bigquery problem, I am gonna close this issue. Good luck.
