### ISSUE TITLE
Wrong output using "to_dataframe" for year above 2099

### ISSUE THREAD

**Issue by davidedironza** [googleapis/python-bigquery#201]
Hi

The bigquery client library is not able to convert the datetime '9999-12-31T00:00:00' from bigquery to dataframe correctly.

```py
from google.cloud import bigquery
sql_statement = f"""SELECT cast('9999-12-31T00:00:00' as datetime)"""
client_bq = bigquery.Client()
df = client_bq.query(sql_statement).to_dataframe()
print(df)
```

Output
`1816-03-29 05:56:08.066277376`

Why this is not possible?

Cheers
Davide

**Comment by plamut** [comment]
Running the query directly in the BigQuery cloud works fine, thus the problem seems to be in result conversion.

I actually wasn't able to reproduce this with a "nice" incorrect result, I actually got a loud exception, the same as reported in #168:
```
pyarrow.lib.ArrowInvalid: Casting from timestamp[us] to timestamp[ns] would result in out of bounds timestamp: 253402214400000000
```
The difference can probably be explained by different installed dependency versions (would you mind sharing them? Thanks!), but all in all it seems like a duplicate of #168.
