### ISSUE TITLE
Python bq client select query date field is returned in invalid date object format  

### ISSUE THREAD

**Issue by vikasbisen** [googleapis/python-bigquery#251]
I am using below method 

```
def my_query_method(query):
  #--This methods query result in form of array of dictionary
  from google.cloud import bigquery
  try:
    client = bigquery.Client()
    query_job = client.query(query)
    results = query_job.result()  # Waits for job to complete. 
    records=[dict(row) for row in query_job]
    print("---record")
    print(records)
    return records
  except:
    print("Issue in query_bigquery_data.")
    traceback.print_exc()
    return None

```

![image](https://user-images.githubusercontent.com/7056113/91616091-f1ca3980-e97c-11ea-82d0-d0871d3adb4d.png)

I am getting record but where ever is TIMESTAMP column I get datetime object which I could not use as in python it is showing it as in valid object.
result i got:-
> ['my_dtts': datetime.datetime(2020, 8, 28, 11, 58, 35, 95868, tzinfo='<'UTC'>')]

another eg.
![image](https://user-images.githubusercontent.com/7056113/91616359-6f8e4500-e97d-11ea-9672-52a94ba13b43.png)

#### Environment details

  - OS type and version: 
  - Python version: `python --version`  Python 3.7.7 
  - pip version: `pip --version`  pip 20.1.1 
  - `google-cloud-bigquery` version: `pip show google-cloud-bigquery`  
Name: google-cloud-bigquery
Version: 1.24.0

Thanks!

**Comment by plamut** [comment]
@vikasbisen Just to understand, why do you say that you cannot use datetime objects?

The value appears correct, i.e. the same as in the table, and datetime objects can be converted to a float timestamp with the `.timestamp()` method? Or is it a problem because the datetime objects returned are _offset-aware_?

Please clarify what the issue and the expected result is, thanks! Do you perhaps expect TIMESTAMP columns to be returned as floating point numbers?
