### ISSUE TITLE
Data order is not preserved when using extract_table

### ISSUE THREAD

**Issue by klaucos** [googleapis/python-bigquery#559]
#### Environment details

  - OS type and version: Ubuntu 20.04 and Ubuntu 18.04 
  - Python version: 3.8.5 also fails on other versions
  - `google-cloud-bigquery` version: 2.6.2

#### Steps to reproduce

Our expectation is that output of sorted table is kept when extracting tables to csv.
This expectation is true on small tables however client.extract_table fails when exporting large amount of data from BigQuery to csv which is unacceptable database behavior.

#### Code example

Example of fail on public dataset.
```python
from google.cloud import bigquery, storage
import pandas as pd

client = bigquery.Client('project_id', 'credentials')
job_config = bigquery.QueryJobConfig()
query_str = """
    SELECT 	time,	time_ts,	CHARACTER_LENGTH(text),	parent,	deleted,
    dead,	ranking FROM `bigquery-public-data.hacker_news.comments`
    ORDER BY time asc
  """
query_job = client.query(query_str, job_config=job_config)
# Start the job and wait for it to complete. Returns `RowIterator`.
rows = query_job.result()
assert query_job.state == 'DONE'

bucket_name = 'your_export_bucket'
path = 'out_tst.csv'
csv_path = f'gs://{bucket_name}/{path}'
extract_job = client.extract_table(
    query_job.destination, csv_path, location='US')
extract_job.result()
assert extract_job.state == 'DONE'

storage_client = storage.Client()
bucket = storage_client.bucket(bucket_name)

blob = bucket.blob(path)
blob.download_to_filename('out_file.csv')

df = pd.read_csv('out_file.csv')
is_sorted = df['time'].is_monotonic_increasing
if not is_sorted:
    df2 = df[['time']].to_csv('out_fail_order.csv')
    print('Not sorted.')
```

This behavior is eroding our trust in BigQuery and Google products. 
I do not think that we would be able to continue with BigQuery if it's unable to properly order a large amount of data, since it markets itself as a database for Big Data.

**Comment by tswast** [comment]
Hi @klaucos ! Thank you for the feedback. I can see how this issue is frustrating for you.

A few points: (1) the BigQuery API does not make guarantees about the order of the data written from extract jobs. If you desire this feature, this repository is not the appropriate place for such a request, as it is a backend issue. I recommend filing an issue here: https://issuetracker.google.com/issues/new?component=187149&template=1162659 and also raising a ticket with Google Cloud support so that it is prioritized.

(2) If you desire a pandas DataFrame in sorted order, we provide a [`to_dataframe()` method](https://googleapis.dev/python/bigquery/latest/generated/google.cloud.bigquery.job.QueryJob.html#google.cloud.bigquery.job.QueryJob.to_dataframe) which uses the higher-throughput BigQuery Storage API by default. Reading from a query results table in this way is guaranteed to return the data in sorted order. We even have some logic to read only from a single stream if an `ORDER BY` is found in the query text. If you do encounter issues with this, please do raise them here.

**Comment by emkornfield** [comment]
There is one other option.  using `EXPORT TABLE AS ... Order by col1, col2, col3` should preserve ordering between exported files.

The BigQuery Storage API only preserves order when number of streams = 1
