### ISSUE TITLE
minor: add integration test for column acls feature

### ISSUE THREAD

**Issue by shollyman** [googleapis/python-bigquery#614]
Once the datacatalog v1 endpoint releases a version with support for the PolicyTagManager client, let's add an integration test to better exercise the column ACL feature.

[This commit](https://github.com/googleapis/googleapis/commit/91eee3d039fbdbadee008393504900287bbc6f43) to proto comments should unblock the datacatalog release.

**Comment by plamut** [comment]
@shollyman There exists a basic [system test](https://github.com/googleapis/python-bigquery/blob/6a48e80bc7d347f381b181f4cf81fef105d0ad0d/tests/system/test_client.py#L333-L382) for setting/updating policy tags on a field, but you mention a `PolicyTagManager` client - presumably this class will be generated?

The synthesis is currently blocked, though, it's failing because of outdated ariifacts in the v4 Bazel image (or something like that).

**Comment by shollyman** [comment]
The system test uses an artificial policy tag.  The change is to create a real taxonomy and policy tag from datacatalog and use it in its place.

https://cloud.google.com/data-catalog/docs/reference/rpc/google.cloud.datacatalog.v1#google.cloud.datacatalog.v1.PolicyTagManager is the client in datacatalog for instantiating the necessary resources.

**Comment by plamut** [comment]
@shollyman Do you know when the API will support `PolicyTagManagerClient`? Soon-ish?

Trying to create a policy tag returns 404 MethodNotImplemented at the time of writing.

**Comment by plamut** [comment]
Should not be blocked anymore.
