### ISSUE TITLE
support google-cloud-bigquery-storage v1

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery#629]
**Is your feature request related to a problem? Please describe.**

I'm filing this in response to internal feedback 186096865

```
Error: module 'google.cloud.bigquery_storage_v1.types' has no attribute 'DataFormat'
```

I believe this is because the customer is using a 1.x version of `google-cloud-bigquery-storage`.

 **Describe the solution you'd like**

(A) Ideally we'd have some code to support either 1.x or 2.x versions of `google-cloud-bigquery-storage`

 **Describe alternatives you've considered**

* (B) Detect when 1.x is used and raise an appropriate exception asking to upgrade to 2.x
* (C) Detect ... and fallback to tabledata.list / getQueryResults + warn that the package should be upgraded

 **Additional context**

N/A

**Comment by tswast** [comment]
If (A) is infeasible, I think (C) is our best fallback, so that `to_dataframe` can still be used, even if it's the slower path.

**Comment by plamut** [comment]
Started experimenting with option `A`, but a concern emerged that this could open a can of worms. In `setup.py` we already [require](https://github.com/googleapis/python-bigquery/commit/cbcb4b86d2d01fb983c20271958b11665e8f7d03#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7) BQ Storage 2.x since version 2.0.0, meaning that if BQ 2.x and BQ Storage 1.x are installed side-by-side should be treated as an environment error IMO.

Sadly, this is quite possible in practice, I managed to `pip` install incompatible versions into a local environment. But updating the library code just to get past the attribute error when using a dependency version already declared too old can reveal other incompatibility issues.

After discussing this with @tswast offline, we think it's less risky to encourage users to upgrade to BQ Storage 2.x by issuing a more user friendly error message when incompatibility is detected. It's a quicker fix, but it still keeps the door open for a "backward compatibility fix" later if too many users are stuck on 1.x versions.
