### ISSUE TITLE
  "You are linking against OpenSSL 1.0.1, which is no longer " E   RuntimeError: You are linking against OpenSSL 1.0.1, which is no longer supported by the OpenSSL project. You need to upgrade to a newer version of OpenSSL.

### ISSUE THREAD

**Issue by EitanBe** [googleapis/python-bigquery#82]
from google.cloud import bigquery
/usr/local/lib/python3.6/site-packages/google/cloud/bigquery/__init__.py:35: in <module>
    from google.cloud.bigquery.client import Client
/usr/local/lib/python3.6/site-packages/google/cloud/bigquery/client.py:54: in <module>
    from google.cloud.client import ClientWithProject
/usr/local/lib/python3.6/site-packages/google/cloud/client.py:27: in <module>
    from google.oauth2 import service_account
/usr/local/lib/python3.6/site-packages/google/oauth2/service_account.py:77: in <module>
    from google.auth import _service_account_info
/usr/local/lib/python3.6/site-packages/google/auth/_service_account_info.py:22: in <module>
    from google.auth import crypt
/usr/local/lib/python3.6/site-packages/google/auth/crypt/__init__.py:43: in <module>
    from google.auth.crypt import rsa
/usr/local/lib/python3.6/site-packages/google/auth/crypt/rsa.py:20: in <module>
    from google.auth.crypt import _cryptography_rsa
/usr/local/lib/python3.6/site-packages/google/auth/crypt/_cryptography_rsa.py:46: in <module>
    _BACKEND = backends.default_backend()
/usr/local/lib/python3.6/site-packages/cryptography/hazmat/backends/__init__.py:15: in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
/usr/local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/__init__.py:7: in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
/usr/local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py:75: in <module>
    from cryptography.hazmat.bindings.openssl import binding
/usr/local/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py:205: in <module>
    _verify_openssl_version(Binding.lib)
/usr/local/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py:169: in _verify_openssl_version
    "You are linking against OpenSSL 1.0.1, which is no longer "
E   RuntimeError: You are linking against OpenSSL 1.0.1, which is no longer supported by the OpenSSL project. You need to upgrade to a newer version of OpenSSL.

openSSL version:
$ openssl version
OpenSSL 1.1.1g  21 Apr 2020

OS:
Ubuntu 14.04.6 LTS \n \l

package:
google-cloud-bigquery==1.24.0

rom cryptography.hazmat.backends.openssl import backend; print(backend.openssl_version_text())
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-574257f7b27c> in <module>
----> 1 from cryptography.hazmat.backends.openssl import backend; print(backend.openssl_version_text())

/usr/local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/__init__.py in <module>
      5 from __future__ import absolute_import, division, print_function
      6
----> 7 from cryptography.hazmat.backends.openssl.backend import backend
      8
      9

/usr/local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py in <module>
     73     _CertificateSigningRequest, _RevokedCertificate
     74 )
---> 75 from cryptography.hazmat.bindings.openssl import binding
     76 from cryptography.hazmat.primitives import hashes, serialization
     77 from cryptography.hazmat.primitives.asymmetric import (

/usr/local/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py in <module>
    203 Binding.init_static_locks()
    204
--> 205 _verify_openssl_version(Binding.lib)

/usr/local/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py in _verify_openssl_version(lib)
    167         else:
    168             raise RuntimeError(
--> 169                 "You are linking against OpenSSL 1.0.1, which is no longer "
    170                 "supported by the OpenSSL project. You need to upgrade to a "
    171                 "newer version of OpenSSL."

RuntimeError: You are linking against OpenSSL 1.0.1, which is no longer supported by the OpenSSL project. You need to upgrade to a newer version of OpenSSL.

**Comment by plamut** [comment]
@EitanBe It appears that you need to update your OpenSSL package on the system. Version 1.0.1 is no longer maintained and has security issues.

**Comment by moshezvi** [comment]
@plamut: That's not an answer. The OpenSSL version reported is 1.1.1. Also - upgrading OpenSSL on the system doesn't really help, because python doesn't want to link with it.

**Comment by plamut** [comment]
@moshezvi Reading it again, my generic answer is indeed not that useful, I should have worded it better - the OpenSSL needs used by Python needs an upgrade, but that does not seem to be the system OpenSSL in this case.

Since Ubuntu 14 is no longer supported except for the extended security maintenance which is not mentioned, it might be necessary to compile Python from source and manually configure the OpenSSL version to link against. Or upgrade the system, if that's feasible.

However, it's essentially a question about the Python installation itself and the system setup, thus not really in the scope of the BigQuery issue tracker.

**Comment by ixje** [comment]
Dropping a note here for whomever is searching for a solution (like I was). Even if you recompile Python with a higher openssl version the error can still show. First, verify your python actually has a high enough version 
```
python -c "import ssl; print(ssl.OPENSSL_VERSION)
```
If it does, then you'll need to rebuild the `cryptography` package, as that is likely still linked to the old openssl version. You can check the linked version as follows
```
(venv) ldd venv/lib/python3.8/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so
	linux-gate.so.1 (0xffffe000)
---> libssl.so.1.0.0 => /usr/lib/i386-linux-gnu/i686/cmov/libssl.so.1.0.0 (0xb763c000) 
	libcrypto.so.1.0.0 => /usr/lib/i386-linux-gnu/i686/cmov/libcrypto.so.1.0.0 (0xb746e000)
	libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xb7452000)
	libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xb72de000)
	libdl.so.2 => /lib/i386-linux-gnu/libdl.so.2 (0xb72d9000)
	/lib/ld-linux.so.2 (0xb777a000)
```

Note: A `pip uninstall cryptography` will likely not work because the annoying error above will be thrown. Manually remove the old `cryptography` package
```
rm -rf venv/lib/python3.8/site-packages/cryptography*
```
Then re-install `cryptography` with `pip install cryptography --no-cache-dir`. Make sure to add the `--no-cache-dir` option or you'll likely be fetching a cached version that has the wrong openssl linked into it. 

If that still builds with the wrong openssl version (if you have multiple version on your system/path) then point it at the right version yourself e.g.
```
LDFLAGS="-L/usr/local/ssl/lib $LDFLAGS" CFLAGS="-I/usr/local/ssl/include $CFLAGS" pip install cryptography --no-cache-dir
```
substitute `/usr/local/ssl/`  with wherever your openssl is installed (see the `OPENSSLDIR` in the output of `openssl version -a`)

Hope that helps
