### ISSUE TITLE
Why placing an upper version limit on Python?

### ISSUE THREAD

**Issue by mars-lan** [googleapis/python-bigquery#856]
https://github.com/googleapis/python-bigquery/blob/cf0b0d862e01e9309407b2ac1a48f0bfe23d520d/setup.py#L135

I understand the desire to "future-proof" against not-yet-released versions, but isn't that what semver is for? Placing this artificial limit causes headaches for downstream consumers of this library as they won't be able to use, say`^3.7` for Python version, in their pyproject.toml. Here's the sample error from poetry
```
The current project's Python requirement (>=3.7,<4.0) is not compatible with some of the required packages Python requirement:
    - google-cloud-bigquery requires Python >=3.6, <3.10, so it will not be satisfied for Python >=3.10,<4.0
```

**Comment by plamut** [comment]
Some of the dependencies (e.g. `pyarrow`) are not guaranteed to work with newer python versions, and it usually takes some time after a new Python version is released for the dependencies to catch up.

IIRC this was the case when Python 3.9 was released, some of the features broke because dependencies were not yet compatible with it.

**Comment by mars-lan** [comment]
Thanks for the explanation. We had our fair share of misfortunes with `pyarrow` when it comes to Apple Silicon. I guess semver is just an utopian view of how the world should work.
