### ISSUE TITLE
QueryJob kms_key_name differs from Table kms_key_name - recent API change?

### ISSUE THREAD

**Issue by neilgluent** [googleapis/python-bigquery#951]
We had code that compared `QueryJob.destination_encryption_configuration.kms_key_name` with the key name we expect to be used. At the end of August 2021 the values were the same but in early September we had a mismatch.

Example code included below and initially taken from Google sample code here: https://cloud.google.com/bigquery/docs/customer-managed-encryption#protect_query

```
from google.cloud import bigquery

location = 'us-west3'
project = 'myproject'
key_name = 'mykey'
ring_name = 'mykring'
dataset_id = 'db1'
table_name = 'table1'

# Construct a BigQuery client object.
client = bigquery.Client(location=location)

# TODO(developer): Set table_id to the ID of the destination table.
# table_id = "your-project.your_dataset.your_table_name"
table_id = f'{project}.{dataset_id}.{table_name}'

# Set the encryption key to use for the destination.
# TODO(developer): Replace this key with a key you have created in KMS.
# kms_key_name = "projects/{}/locations/{}/keyRings/{}/cryptoKeys/{}".format(
#     your-project, location, your-ring, your-key
# )
kms_key_name = "projects/{}/locations/{}/keyRings/{}/cryptoKeys/{}".format(
    project, location, ring_name, key_name
)

job_config = bigquery.QueryJobConfig(
    destination=table_id,
    destination_encryption_configuration=bigquery.EncryptionConfiguration(
        kms_key_name=kms_key_name
    ),
)

# Start the query, passing in the extra configuration.
query_job = client.query(
    "SELECT 17 AS my_col;", job_config=job_config
)  # Make an API request.
query_job.result()  # Wait for the job to complete.
print('query_job.destination_encryption_configuration.kms_key_name',
      query_job.destination_encryption_configuration.kms_key_name)

table = client.get_table(table_id)  # Make an API request.
print('table.encryption_configuration.kms_key_name',
      table.encryption_configuration.kms_key_name)
if table.encryption_configuration.kms_key_name == kms_key_name:
    print("The destination table is written using the encryption configuration")
```

The output from the script is below, note the suffix of `/cryptoKeyVersions/1` on the first line:

```
$ python3 ~/kms_test.py
query_job.destination_encryption_configuration.kms_key_name projects/myproject/locations/us-west3/keyRings/mykring/cryptoKeys/mykey/cryptoKeyVersions/1
table.encryption_configuration.kms_key_name projects/myproject/locations/us-west3/keyRings/mykring/cryptoKeys/mykey
The destination table is written using the encryption configuration
```

Recently the values for `query_job.destination_encryption_configuration.kms_key_name` and `table.encryption_configuration.kms_key_name` were the same. As you can see above they now differ.

There are three questions we would like to answer:

1. Should `destination_encryption_configuration.kms_key_name` match the value we put into `bigquery.QueryJobConfig`? 
2. We cannot find a release note/changelog reference to this key name value change. If it was an intentional change, is it documented anywhere?
3. If the change was an intentional, is there a subscription for advance notification of potentially breaking changes we can subscribe to?

**Comment by tswast** [comment]
This change was intentional. The KMS team requested that BigQuery share the version information so that customers can know what versions are safe to delete (part of key rotation).

I'm reaching out to the folks responsible for the change now to see how this was communicated to customers.

**Comment by neilgluent** [comment]
Thanks for the update, and thanks for checking communication.

**Comment by tswast** [comment]
I learned a bit more about the change. In May 2021, affected customers were identified and an email was sent out. From what I can tell, this change has not been published in https://cloud.google.com/bigquery/docs/release-notes but in my opinion it should have been in May when the change was known to be coming. I'll reach out to the relevant folks to try to make sure this doesn't catch folks by surprise in the future.

Email contents:

**Update your KMS-enabled BigQuery tools by September 1, 2021,  to parse cryptoKeyVersions tokens.**

Dear Google Cloud Platform Customer,

We are writing to let you know that starting September 1, 2021,  BigQuery will start reporting the cryptoKeyVersions of Cloud Key Management Service (KMS) keys. This key is used to protect BigQuery tables and models. After September 1, 2021, the EncryptionConfiguration kmsKeyName field in the table and model metadata will display KMS key names in the following format:

```
projects/.../locations/.../keyRings/.../cryptoKeys/.../cryptoKeyVersions/...
```

The previous format was:

```
projects/.../locations/.../keyRings/.../cryptoKeys/...
```

What do I need to do?

If you have KMS-enabled BigQuery tools or services that parse the KMS key name field, kmsKeyName, update them to support a KMS key name with or without the cryptoKeyVersions token before September 1, 2021. Your tools must support both formats, since the changes to the key name display formats will be applied gradually.

What remains unchanged?

When specifying a KMS key to encrypt a table or model, you should continue to provide the key name without the cryptoKeyVersions (projects/.../locations/.../keyRings/.../cryptoKeys/...). KMS uses the primary key versions of the key to protect the table or model.

Because the kmsKeyName field on a dataset is the default for newly created resources beneath it, datasets will continue to accept and display KMS keys without the cryptoKeyVersions.
